### ISSUE TITLE
Need help: Solved

### ISSUE THREAD

**Issue by filippobuletto** [Autocrit/Asus-ROG-STRIX-H370-I-GAMING-Hackintosh-Guide#4]
EDIT:

Solved, the issue was with multiple ethernete kext present at the same time, you have to choose and use only one at a time.

**Comment by Autocrit** [comment]
I've never had to create the EFI partition in Windows so maybe the guide isn't so useful but you have a number of drivers that aren't mentioned by CorpNewt.

When installing Clover, only 4 drivers (ApfsDriverLoader.efi, AptioMemoryFix.efi, EmuVariableUefi.efi and HFSPlus.efi) get installed in /Volumes/EFI/EFI/CLOVER/drivers/UEFI. There is no BIOS folder which I assume is controlled by the "Install for UEFI booting only" option.

The kexts look OK. I just use the Intel ethernet port so have IntelMausiEthernet.kext but not RealtekRTL8111.kext.

**Comment by filippobuletto** [comment]
Thanks! I'm trying it and if I'll not be successful I'll get a mac and use clover installer like you've done!

Do you mind share an archive of your EFI partition? I've tried the one you posted on Reddit but is expired... If not, no problem!
